### ISSUE TITLE
Create XQUERY with expected result for blood pressure example 

### ISSUE THREAD

**Issue by bjornna** [serefarikan/aql-discussion#2]
How to create XQUERY to get the expected result for the blood pressure example? 

This is expected (I think): 
https://github.com/bjornna/openehr-conformance/blob/master/aql/case1.1-permutation_bp/index.adoc#aql-2---with-point_event

**Comment by serefarikan** [comment]
solved in commit https://github.com/serefarikan/aql-discussion/commit/3fdd8abe523adbd703159e1f4cb4680716a757f1
